# Generated by Django 4.1.7 on 2023-02-16 14:32

from django.db import migrations, models
import projects.models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='postproject',
            name='imagem',
            field=models.ImageField(default=1, upload_to=projects.models.get_img_upload_path),
            preserve_default=False,
        ),
    ]
