# Generated by Django 4.1.7 on 2023-03-13 14:20

from django.db import migrations, models
import django.db.models.deletion
import members.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Achievements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('achievementsimg', models.ImageField(upload_to=members.models.get_img_upload_path)),
                ('name', models.CharField(max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CategoriaMenbers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Members',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(upload_to=members.models.get_img_upload_path)),
                ('name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=300)),
                ('number', models.IntegerField(max_length=200)),
                ('curriculum', models.URLField()),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('achive', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.achievements')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.categoriamenbers')),
            ],
        ),
    ]
